// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: myImportPkg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_myImportPkg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_myImportPkg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "myPkg.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_myImportPkg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_myImportPkg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_myImportPkg_2eproto;
namespace package {
class MyPackage;
struct MyPackageDefaultTypeInternal;
extern MyPackageDefaultTypeInternal _MyPackage_default_instance_;
}  // namespace package
PROTOBUF_NAMESPACE_OPEN
template<> ::package::MyPackage* Arena::CreateMaybeMessage<::package::MyPackage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace package {

// ===================================================================

class MyPackage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:package.MyPackage) */ {
 public:
  inline MyPackage() : MyPackage(nullptr) {}
  ~MyPackage() override;
  explicit constexpr MyPackage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  MyPackage(const MyPackage& from);
  MyPackage(MyPackage&& from) noexcept
    : MyPackage() {
    *this = ::std::move(from);
  }

  inline MyPackage& operator=(const MyPackage& from) {
    CopyFrom(from);
    return *this;
  }
  inline MyPackage& operator=(MyPackage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const MyPackage& default_instance() {
    return *internal_default_instance();
  }
  static inline const MyPackage* internal_default_instance() {
    return reinterpret_cast<const MyPackage*>(
               &_MyPackage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MyPackage& a, MyPackage& b) {
    a.Swap(&b);
  }
  inline void Swap(MyPackage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MyPackage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  MyPackage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<MyPackage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const MyPackage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const MyPackage& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MyPackage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "package.MyPackage";
  }
  protected:
  explicit MyPackage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInfoFieldNumber = 1,
    kSubPkgFieldNumber = 2,
  };
  // string info = 1;
  void clear_info();
  const std::string& info() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_info(ArgT0&& arg0, ArgT... args);
  std::string* mutable_info();
  PROTOBUF_NODISCARD std::string* release_info();
  void set_allocated_info(std::string* info);
  private:
  const std::string& _internal_info() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_info(const std::string& value);
  std::string* _internal_mutable_info();
  public:

  // .subPackage.MyPackage subPkg = 2;
  bool has_subpkg() const;
  private:
  bool _internal_has_subpkg() const;
  public:
  void clear_subpkg();
  const ::subPackage::MyPackage& subpkg() const;
  PROTOBUF_NODISCARD ::subPackage::MyPackage* release_subpkg();
  ::subPackage::MyPackage* mutable_subpkg();
  void set_allocated_subpkg(::subPackage::MyPackage* subpkg);
  private:
  const ::subPackage::MyPackage& _internal_subpkg() const;
  ::subPackage::MyPackage* _internal_mutable_subpkg();
  public:
  void unsafe_arena_set_allocated_subpkg(
      ::subPackage::MyPackage* subpkg);
  ::subPackage::MyPackage* unsafe_arena_release_subpkg();

  // @@protoc_insertion_point(class_scope:package.MyPackage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr info_;
  ::subPackage::MyPackage* subpkg_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_myImportPkg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MyPackage

// string info = 1;
inline void MyPackage::clear_info() {
  info_.ClearToEmpty();
}
inline const std::string& MyPackage::info() const {
  // @@protoc_insertion_point(field_get:package.MyPackage.info)
  return _internal_info();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void MyPackage::set_info(ArgT0&& arg0, ArgT... args) {
 
 info_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:package.MyPackage.info)
}
inline std::string* MyPackage::mutable_info() {
  std::string* _s = _internal_mutable_info();
  // @@protoc_insertion_point(field_mutable:package.MyPackage.info)
  return _s;
}
inline const std::string& MyPackage::_internal_info() const {
  return info_.Get();
}
inline void MyPackage::_internal_set_info(const std::string& value) {
  
  info_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* MyPackage::_internal_mutable_info() {
  
  return info_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* MyPackage::release_info() {
  // @@protoc_insertion_point(field_release:package.MyPackage.info)
  return info_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void MyPackage::set_allocated_info(std::string* info) {
  if (info != nullptr) {
    
  } else {
    
  }
  info_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), info,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (info_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    info_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:package.MyPackage.info)
}

// .subPackage.MyPackage subPkg = 2;
inline bool MyPackage::_internal_has_subpkg() const {
  return this != internal_default_instance() && subpkg_ != nullptr;
}
inline bool MyPackage::has_subpkg() const {
  return _internal_has_subpkg();
}
inline const ::subPackage::MyPackage& MyPackage::_internal_subpkg() const {
  const ::subPackage::MyPackage* p = subpkg_;
  return p != nullptr ? *p : reinterpret_cast<const ::subPackage::MyPackage&>(
      ::subPackage::_MyPackage_default_instance_);
}
inline const ::subPackage::MyPackage& MyPackage::subpkg() const {
  // @@protoc_insertion_point(field_get:package.MyPackage.subPkg)
  return _internal_subpkg();
}
inline void MyPackage::unsafe_arena_set_allocated_subpkg(
    ::subPackage::MyPackage* subpkg) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(subpkg_);
  }
  subpkg_ = subpkg;
  if (subpkg) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:package.MyPackage.subPkg)
}
inline ::subPackage::MyPackage* MyPackage::release_subpkg() {
  
  ::subPackage::MyPackage* temp = subpkg_;
  subpkg_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::subPackage::MyPackage* MyPackage::unsafe_arena_release_subpkg() {
  // @@protoc_insertion_point(field_release:package.MyPackage.subPkg)
  
  ::subPackage::MyPackage* temp = subpkg_;
  subpkg_ = nullptr;
  return temp;
}
inline ::subPackage::MyPackage* MyPackage::_internal_mutable_subpkg() {
  
  if (subpkg_ == nullptr) {
    auto* p = CreateMaybeMessage<::subPackage::MyPackage>(GetArenaForAllocation());
    subpkg_ = p;
  }
  return subpkg_;
}
inline ::subPackage::MyPackage* MyPackage::mutable_subpkg() {
  ::subPackage::MyPackage* _msg = _internal_mutable_subpkg();
  // @@protoc_insertion_point(field_mutable:package.MyPackage.subPkg)
  return _msg;
}
inline void MyPackage::set_allocated_subpkg(::subPackage::MyPackage* subpkg) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(subpkg_);
  }
  if (subpkg) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<
            ::PROTOBUF_NAMESPACE_ID::MessageLite>::GetOwningArena(
                reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(subpkg));
    if (message_arena != submessage_arena) {
      subpkg = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, subpkg, submessage_arena);
    }
    
  } else {
    
  }
  subpkg_ = subpkg;
  // @@protoc_insertion_point(field_set_allocated:package.MyPackage.subPkg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace package

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_myImportPkg_2eproto
